/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.univers.vistas;

/**
 *
 * @author javie
 */
public class AlumnosXmaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlumnosXmaterias
     */
    public AlumnosXmaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        materiacombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaalumno = new javax.swing.JTable();
        salirconsultaboton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Listado de Alumnos por Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, -1, -1));

        jLabel2.setText("Seleccione una materia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 65, -1, -1));

        materiacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiacomboActionPerformed(evt);
            }
        });
        getContentPane().add(materiacombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 60, 212, -1));

        tablaalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaalumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 355, 192));

        salirconsultaboton.setText("Salir");
        salirconsultaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirconsultabotonActionPerformed(evt);
            }
        });
        getContentPane().add(salirconsultaboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materiacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiacomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiacomboActionPerformed

    private void salirconsultabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirconsultabotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirconsultabotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materiacombo;
    private javax.swing.JButton salirconsultaboton;
    private javax.swing.JTable tablaalumno;
    // End of variables declaration//GEN-END:variables
}
