/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.univers.vistas;

import gestion.univers.accesoADatos.AlumnoData;
import gestion.univers.accesoADatos.Conexion;
import gestion.univers.accesoADatos.InscripcionData;
import gestion.univers.accesoADatos.MateriaData;
import gestion.univers.entidades.Alumno;
import gestion.univers.entidades.Inscripcion;
import gestion.univers.entidades.Materia;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javie
 */
public class ManipulacionNotas extends javax.swing.JInternalFrame {

    Connection con = null;
    ArrayList Alista;
    AlumnoData alumno = new AlumnoData();
    ArrayList<Materia> Mlista;
    MateriaData materia = new MateriaData();
    DefaultTableModel modelo;
    
    public ManipulacionNotas() {
        initComponents();
        
        modelo = new DefaultTableModel();
        con = Conexion.getConexion();
        Alista = new ArrayList();
        llenarcombo(); 
        armaCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carganotacombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        carganotatabla = new javax.swing.JTable();
        guardarnotaboton = new javax.swing.JButton();
        salirnotaboton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Carga de Notas");

        jLabel2.setText("Seleccione un alumno:");

        carganotatabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carganotatabla);

        guardarnotaboton.setText("Guardar");

        salirnotaboton.setText("Salir");
        salirnotaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirnotabotonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(carganotacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(guardarnotaboton)
                .addGap(153, 153, 153)
                .addComponent(salirnotaboton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(carganotacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarnotaboton)
                    .addComponent(salirnotaboton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void llenarcombo () {
        
       carganotacombo.removeAllItems();
       Alista = (ArrayList) alumno.ListarAlumnos();
       Iterator iterador = Alista.iterator();
       while(iterador.hasNext()){
           Alumno alu = (Alumno) iterador.next();
           carganotacombo.addItem(alu.toString());   
       }
        
    }
    public void armaCabeceraTabla() {

        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("Codigo");
        columnas.add("Nombre");
        columnas.add("Nota");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        carganotatabla.setModel(modelo);

    }
    public void llenartabla() {
        InscripcionData inscripcion = new InscripcionData();
        Inscripcion insc = new Inscripcion();

        Alumno alu = (Alumno) carganotacombo.getSelectedItem();
        Mlista = (ArrayList) inscripcion.ObtenerInscripcionesPorAlumno(alu.getIdAlumno());
        for (Materia mate : Mlista) {
            modelo.addRow(new Object[]{mate.getIdMateria(), mate.getNombre(), insc.getNota()});
           
        }
    }
    
    private void salirnotabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirnotabotonActionPerformed
     
         this.dispose();
        
    }//GEN-LAST:event_salirnotabotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carganotacombo;
    private javax.swing.JTable carganotatabla;
    private javax.swing.JButton guardarnotaboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salirnotaboton;
    // End of variables declaration//GEN-END:variables
}
